// Generated by Atlas for @angular-architects/native-federation.
// Edit atlas.config.ts and application source; do not hand-edit this compatibility file.
// Native Federation requires this exact filename next to the Angular tsconfig.
const { readdirSync, existsSync } = require("node:fs");
const { join } = require("node:path");
const { withNativeFederation } = require("@angular-architects/native-federation/config");

const componentsRoot = join(__dirname, "src/exported-components");
const componentExposes = existsSync(componentsRoot)
  ? Object.fromEntries(readdirSync(componentsRoot, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => [`./components/${entry.name}`, `./src/exported-components/${entry.name}/index.ts`]))
  : {};

module.exports = withNativeFederation({
  name: "atlas_mobile_host",
  exposes: {},
  // Product dependencies stay inside this build so hosts never impose their versions.
  shared: {},
  skip: ["rxjs/ajax", "rxjs/fetch", "rxjs/testing", "rxjs/webSocket"]
});
